// Code generated by MockGen. DO NOT EDIT.
// Source: ./shelf_block.go

// Package mock_warehousemanagementservice is a generated GoMock package.
package mock_warehousemanagementservice

import (
	context "context"
	reflect "reflect"
	warehousemanagementservice "warehouse-management-service"

	gomock "github.com/golang/mock/gomock"
)

// MockShelfBlockService is a mock of ShelfBlockService interface.
type MockShelfBlockService struct {
	ctrl     *gomock.Controller
	recorder *MockShelfBlockServiceMockRecorder
}

// MockShelfBlockServiceMockRecorder is the mock recorder for MockShelfBlockService.
type MockShelfBlockServiceMockRecorder struct {
	mock *MockShelfBlockService
}

// NewMockShelfBlockService creates a new mock instance.
func NewMockShelfBlockService(ctrl *gomock.Controller) *MockShelfBlockService {
	mock := &MockShelfBlockService{ctrl: ctrl}
	mock.recorder = &MockShelfBlockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShelfBlockService) EXPECT() *MockShelfBlockServiceMockRecorder {
	return m.recorder
}

// CreateShelfBlock mocks base method.
func (m *MockShelfBlockService) CreateShelfBlock(ctx context.Context, shelfBlock warehousemanagementservice.ShelfBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShelfBlock", ctx, shelfBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShelfBlock indicates an expected call of CreateShelfBlock.
func (mr *MockShelfBlockServiceMockRecorder) CreateShelfBlock(ctx, shelfBlock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShelfBlock", reflect.TypeOf((*MockShelfBlockService)(nil).CreateShelfBlock), ctx, shelfBlock)
}

// DeleteShelfBlockById mocks base method.
func (m *MockShelfBlockService) DeleteShelfBlockById(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShelfBlockById", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShelfBlockById indicates an expected call of DeleteShelfBlockById.
func (mr *MockShelfBlockServiceMockRecorder) DeleteShelfBlockById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShelfBlockById", reflect.TypeOf((*MockShelfBlockService)(nil).DeleteShelfBlockById), ctx, id)
}

// GetShelfBlockById mocks base method.
func (m *MockShelfBlockService) GetShelfBlockById(ctx context.Context, id string) (warehousemanagementservice.ShelfBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShelfBlockById", ctx, id)
	ret0, _ := ret[0].(warehousemanagementservice.ShelfBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShelfBlockById indicates an expected call of GetShelfBlockById.
func (mr *MockShelfBlockServiceMockRecorder) GetShelfBlockById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShelfBlockById", reflect.TypeOf((*MockShelfBlockService)(nil).GetShelfBlockById), ctx, id)
}

// UpdateShelfBlock mocks base method.
func (m *MockShelfBlockService) UpdateShelfBlock(ctx context.Context, shelfBlock warehousemanagementservice.ShelfBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShelfBlock", ctx, shelfBlock)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShelfBlock indicates an expected call of UpdateShelfBlock.
func (mr *MockShelfBlockServiceMockRecorder) UpdateShelfBlock(ctx, shelfBlock interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShelfBlock", reflect.TypeOf((*MockShelfBlockService)(nil).UpdateShelfBlock), ctx, shelfBlock)
}
