# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: warehouse-management-system

on:
 push:
#    paths:
#      - warehouse-management-service/**
#  pull_request:
#    paths:
#      - warehouse-management-service/**

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          cache: false
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./warehouse-management-service

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: |
          cd warehouse-management-service
          go build -v ./cmd/wms

      - name: Test
        env:
          CONFIG_FILE_PATH: ""
        run: |
          cd warehouse-management-service
          go test -v ./...

      - name: Deploy
        run: |
          ls
          sftp -i ./wms ${{ secrets.SERVER_USER }}@${{ secrets.SERVER }}